spring:
  datasource:
    url: jdbc:postgresql://service-db:5432/clevertec-banking?currentSchema=credit
    username: clevertec
    password: banking
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: credit
  liquibase:
    default-schema: credit
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: credit
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
    port: 5672
    host: rabbitmq
    username: clevertec
    password: banking
clevertec:
  rabbit:
    consumer:
      queue:
        credit-queue: credit-details
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true