spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATA_BASE}
    username: admin
    password: admin
  cache:
    redis:
      time-to-live: 7
  data:
    redis:
      port: 6379
clevertec:
  exceptions:
    handler:
      enable: false