spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springBootHW
    username: admin
    password: admin
  cache:
    clevertec:
      redis:
        redis-host: localhost
        redis-port: 6379
        prefix-cache-name: prefix
        ttlSecond: 2
clevertec:
  exceptions:
    handler:
      enable: false